In [1]:
import torch


In [35]:
# B,L,D = 2,4,2
B,M,L,D = 64,6,30,2 # batch_size, modes, pred_len, data_dim
my_tensor = torch.randn(B,M,L,D)
conf = torch.randn(B,M)
# print("my_tensor: ", my_tensor)
my_tensor.shape

torch.Size([2, 2, 2, 2])

In [44]:
def get_sub_tensor(my_tensor, idx):
    return my_tensor[torch.arange(B), idx, :, :].squeeze()

In [45]:
# best_idx = torch.tensor([3,0])
idx = torch.softmax(conf,dim=1)
best_idx = idx.argmax(1)

my_tensor_sub = get_sub_tensor(my_tensor, best_idx)
# print(my_tensor_sub, my_tensor_sub.shape)
my_tensor_sub.shape

torch.Size([2, 2, 2])

In [37]:
my_tensor

tensor([[[[-0.3214, -0.7907],
          [-0.7917,  0.3795]],

         [[ 1.6477,  0.4171],
          [-1.7287, -0.8398]]],


        [[[ 0.3904, -0.0180],
          [ 1.0596, -0.0710]],

         [[ 0.2248,  1.0067],
          [ 0.2245,  0.6394]]]])

In [38]:
my_tensor_sub

tensor([[[ 1.6477,  0.4171],
         [-1.7287, -0.8398]],

        [[ 0.3904, -0.0180],
         [ 1.0596, -0.0710]]])

In [39]:
best_idx

tensor([1, 0])